footprint: [[-0.5, -0.35], [-0.5, 0.35], [0.5, 0.35], [0.5, -0.35]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_layer_points:
    observation_sources: points
    points:
        {
            data_type: PointCloud2,
            clearing: true,
            marking: true,
            topic: camera/depth/points,
            min_obstacle_height: 0.1,
            expected_update_rate: 5
        }

obstacles_layer_laser:
    observation_sources: laser
    laser:
        {
            data_type: LaserScan,
            marking: true,
            clearing: true,
            topic: scan,
            inf_is_valid: true,
        }

inflation:
    inflation_radius: 1.0
